Import('env MainHeaderPaths MainLibraryPaths MainLibraryLinks')

SConscript('libs/SConscript',exports='env MainLibraryPaths MainLibraryLinks')

sourcePaths = ['main.cpp', 'input.cpp', "OgreCore.cpp", "BaseScene.cpp", 
"SceneOne.cpp", "FloorManager.cpp", "DynamicObject.cpp", 'LevelManager.cpp'];


env.Append(CPPPATH = MainHeaderPaths);
env.Append(LIBPATH = MainLibraryPaths);
env.Append(LIBS = MainLibraryLinks);
env.Program(target = 'program', source = sourcePaths );

